# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAuRwn_oMK--3J1BRGF_uu94__a-WKxG
"""

!pip install -q -U google-generativeai

# 1. Gerekli kütüphaneleri yükle
!pip install -q -U google-generativeai pyTelegramBotAPI nest_asyncio
from flask import Flask
from threading import Thread
# !pip install google-genai python-telegram-bot nest_asyncio

import asyncio
import nest_asyncio
import datetime
import os
from collections import deque
from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, MessageHandler, filters
from google import genai

app = Flask('')
# --- AYARLAR ---
nest_asyncio.apply()
@app.route('/')
def home():
    return "Zenithar Bot Aktif ve 7/24 Uyanık!"

# İŞTE BURAYA YAZIYORSUN:
def run():
    # Render'ın verdiği portu al, yoksa 8080 kullan
    port = int(os.environ.get("PORT", 8080)) 
    print(f"Flask {port} portunda başlatılıyor...")
    app.run(host='0.0.0.0', port=port)

def keep_alive():
    t = Thread(target=run)
    t.start()

# ÖNEMLİ: Token'ın içinde ":" olduğundan emin ol!
TELEGRAM_TOKEN = "8531416366:AAGD-KEXr5FRKO5O-woh54bO4yn8Vdj2oKY"
GOOGLE_API_KEY = "AIzaSyBtAQLG5jw-nIG83Pa1w2oDi5GvOKZ-CPQ"

# Yeni Nesil Gemini İstemcisi
client = genai.Client(api_key=GOOGLE_API_KEY)

# Hafıza ve Cooldown Takibi
group_history = deque(maxlen=500)
last_usage = {}  # {chat_id: son_kullanim_zamani}
COOLDOWN_MINUTES = 10

# --- BOT FONKSİYONLARI ---

async def record_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.message and update.message.text:
        user = update.effective_user.first_name
        text = update.message.text
        group_history.append(f"{user}: {text}")

async def summarize_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    now = datetime.datetime.now()

    # --- 1. BEKLEME SÜRESİ KONTROLÜ ---
    if chat_id in last_usage:
        gecen_sure = now - last_usage[chat_id]
        kalan_saniye = (COOLDOWN_MINUTES * 60) - gecen_sure.total_seconds()

        if kalan_saniye > 0:
            dakika = int(kalan_saniye // 60)
            saniye = int(kalan_saniye % 60)
            await update.message.reply_text(
                f"🛑 Henüz hazır değilim!\n\nTekrar özet çıkarabilmek için {dakika} dakika {saniye} saniye daha beklemeniz gerekiyor. Zenithar'ı kızdırmamalıyım."
            )
            return

    # --- 2. MESAJ KONTROLÜ ---
    msg_text = update.message.text.lower().replace(" ", "")
    count = 200 if "200" in msg_text else 400 if "400" in msg_text else 0
    if count == 0: return

    if len(group_history) < 10:
        await update.message.reply_text("❌ Hafızada yeterli mesaj yok (En az 10 mesaj gerekli).")
        return

    status_msg = await update.message.reply_text("⏳ Yukarıdaki mesajları okuyorum. Lütfen bekle...")

    full_text = "\n".join(list(group_history)[-count:])
    prompt = f"Aşağıdaki konuşmaları samimi ve esprili bir dille özetle. Özel kurallar: /n 1: mesajlar arasında Zenithar, Gizem veya Cıtkırıldı varsa bunları özete mutlaka dahil et ama hep de onlardan bahsetme diğerleriyle eşit derecede olsun. /n Kural:2 Bu mesajın dakikası tek sayı ise ve özette Gizem varsa gizemden Kralicemiz Gizem şeklinde bahset çift sayı ise sadece Gizem de. /n 3: özette Felicia ya da Tuna varsa onlarla dalga geç ve onları biraz aşağıla ama abartma sadece hafif dokundur. Eğer yoklarsa isimlerini anma.  /n kural 4: Özet içerisinde asla *(yıldız) işareti kullanma  /n kural:5 yazılanların hepsini 'o şunu dedi bu bunu dedi' gibi aynen yazmak yerine daha çok olay olarak özetle. Daha çok ince espri kat. Bir kişinin ismi tek harften oluşabilir örneğin ''F'' ile ''Felicia'yı karıştırma, özet maksimum 500 kelimelik olsun \n\n{full_text}"

    # --- 3. ÜRETİM VE COOLDOWN BAŞLATMA ---
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        await status_msg.edit_text(f"📝 CHAT ÖZETİ:\n{response.text}")

        # Başarılı olursa süreyi kaydet
        last_usage[chat_id] = now

    except Exception as e:
        await status_msg.edit_text(f"⚠️ Hata: {e}")

# --- ANA ÇALIŞTIRICI ---
async def main():
    app = ApplicationBuilder().token(TELEGRAM_TOKEN).build()

    app.add_handler(MessageHandler(filters.Regex(r'(?i)^/son\s*(200|400)$'), summarize_command))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), record_message))

    print("✅ Bot Aktif. 30 dakikalık koruma devrede.")
    await app.initialize()
    await app.start()
    await app.updater.start_polling(drop_pending_updates=True)
    while True: await asyncio.sleep(60)

if __name__ == "__main__":
    await main()

# 1. Gerekli kütüphaneleri yükle
!pip install -q -U google-generativeai pyTelegramBotAPI nest_asyncio
from flask import Flask
from threading import Thread
# !pip install google-genai python-telegram-bot nest_asyncio

import asyncio
import nest_asyncio
import datetime
from collections import deque
from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, MessageHandler, filters
from google import genai

app = Flask('')
# --- AYARLAR ---
nest_asyncio.apply()

# ÖNEMLİ: Token'ın içinde ":" olduğundan emin ol!
TELEGRAM_TOKEN = "8531416366:AAGD-KEXr5FRKO5O-woh54bO4yn8Vdj2oKY"
GOOGLE_API_KEY = "AIzaSyBtAQLG5jw-nIG83Pa1w2oDi5GvOKZ-CPQ"

# Yeni Nesil Gemini İstemcisi
client = genai.Client(api_key=GOOGLE_API_KEY)

# Hafıza ve Cooldown Takibi
group_history = deque(maxlen=500)
last_usage = {}  # {chat_id: son_kullanim_zamani}
COOLDOWN_MINUTES = 10

# --- BOT FONKSİYONLARI ---

async def record_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.message and update.message.text:
        user = update.effective_user.first_name
        text = update.message.text
        group_history.append(f"{user}: {text}")

async def summarize_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    now = datetime.datetime.now()

    # --- 1. BEKLEME SÜRESİ KONTROLÜ ---
    if chat_id in last_usage:
        gecen_sure = now - last_usage[chat_id]
        kalan_saniye = (COOLDOWN_MINUTES * 60) - gecen_sure.total_seconds()

        if kalan_saniye > 0:
            dakika = int(kalan_saniye // 60)
            saniye = int(kalan_saniye % 60)
            await update.message.reply_text(
                f"🛑 Henüz hazır değilim!\n\nTekrar özet çıkarabilmek için {dakika} dakika {saniye} saniye daha beklemeniz gerekiyor. Zenithar'ı kızdırmamalıyım."
            )
            return

    # --- 2. MESAJ KONTROLÜ ---
    msg_text = update.message.text.lower().replace(" ", "")
    count = 200 if "200" in msg_text else 400 if "400" in msg_text else 0
    if count == 0: return

    if len(group_history) < 10:
        await update.message.reply_text("❌ Hafızada yeterli mesaj yok (En az 10 mesaj gerekli).")
        return

    status_msg = await update.message.reply_text("⏳ Yukarıdaki mesajları okuyorum. Lütfen bekle...")

    full_text = "\n".join(list(group_history)[-count:])
    prompt = f"Aşağıdaki konuşmaları samimi ve esprili bir dille özetle. Özel kurallar: /n 1: mesajlar arasında Zenithar, Gizem veya Cıtkırıldı varsa bunları özete mutlaka dahil et ama hep de onlardan bahsetme diğerleriyle eşit derecede olsun. /n Kural:2 Bu mesajın dakikası tek sayı ise ve özette Gizem varsa gizemden Kralicemiz Gizem şeklinde bahset çift sayı ise sadece Gizem de. /n 3: özette Felicia ya da Tuna varsa onlarla dalga geç ve onları biraz aşağıla ama abartma sadece hafif dokundur. Eğer yoklarsa isimlerini anma.  /n kural 4: Özet içerisinde asla *(yıldız) işareti kullanma  /n kural:5 yazılanların hepsini 'o şunu dedi bu bunu dedi' gibi aynen yazmak yerine daha çok olay olarak özetle. Daha çok ince espri kat. Bir kişinin ismi tek harften oluşabilir örneğin ''F'' ile ''Felicia'yı karıştırma, özet maksimum 500 kelimelik olsun \n\n{full_text}"

    # --- 3. ÜRETİM VE COOLDOWN BAŞLATMA ---
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        await status_msg.edit_text(f"📝 CHAT ÖZETİ:\n{response.text}")

        # Başarılı olursa süreyi kaydet
        last_usage[chat_id] = now

    except Exception as e:
        await status_msg.edit_text(f"⚠️ Hata: {e}")

# --- ANA ÇALIŞTIRICI ---
async def main():
    app = ApplicationBuilder().token(TELEGRAM_TOKEN).build()

    app.add_handler(MessageHandler(filters.Regex(r'(?i)^/son\s*(200|400)$'), summarize_command))
    app.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), record_message))

    print("✅ Bot Aktif. 30 dakikalık koruma devrede.")
    await app.initialize()
    await app.start()
    await app.updater.start_polling(drop_pending_updates=True)
    while True: await asyncio.sleep(60)

if __name__ == "__main__":
    await main()

import google.generativeai as genai

# Kendi API anahtarını buraya koy
genai.configure(api_key="AIzaSyBtAQLG5jw-nIG83Pa1w2oDi5GvOKZ-CPQ")

print("Erişebildiğin Modeller:")
for m in genai.list_models():
    if 'generateContent' in m.supported_generation_methods:
        print(f"-> {m.name}")
